services:
  backend:
    build: 
      context: ./ichGram_backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3000:3001"
    environment:
      - PORT=3000
      - FRONTEND_URL=http://localhost:5173
      - DATABASE_URI=mongodb+srv://yuliia:sRmdXNHpJeSVnfum@cluster0.s8odekr.mongodb.net/finish-project?retryWrites=true&w=majority&
      - JWT_SECRET=iMnVpN55LotTB0N5gRdlVx5e34PdDK3k
      - CLOUDINARY_CLOUD_NAME=dmmjnsxo4
      - CLOUDINARY_API_KEY=135334814883789
      - CLOUDINARY_API_SECRET=pbGwrR2T5cAEWJYcXDQkLwWXorQ
      - GMX_EMAIL=yuli.pomazan@gmx.de
      - GMX_PASSWORD=tGmojs3bWkNO
  frontend:
    build: 
      context: ./ichGram_frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:3000/api
    ports:
      - "5173:80"
    depends_on:
      - backend